{
 "title": "FastAPI Observability",
 "tags": [
  "fastapi",
  "prometheus",
  "mlops"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "handler",
    "query": "label_values(http_requests_total, handler)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests / second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler=~\"$handler\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Error rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\",handler=~\"$handler\"}[5m])) / sum(rate(http_requests_total{handler=~\"$handler\"}[5m]))",
     "legendFormat": "5xx ratio"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler=~\"$handler\"}[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Latency p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{handler=~\"$handler\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}